<?php

/**
 * This is NOT a drop-in file — Laravel 11's real bootstrap/app.php has a
 * lot of framework wiring generated by `laravel new` that must stay
 * intact. This shows exactly what to ADD to the `->withMiddleware(...)`
 * callback in your real bootstrap/app.php so the routes/api.php and
 * EnsurePermission middleware in this phase actually work:
 */

use App\Http\Middleware\EnsurePermission;
use App\Http\Middleware\EnsureRole;
use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    // ... existing ->withRouting(...) etc unchanged ...
    ->withMiddleware(function (Middleware $middleware) {
        // 1. Enable Sanctum's stateful API middleware (needed regardless of
        //    whether you end up using token or cookie auth, since the
        //    `api` group should still recognise Sanctum guards):
        $middleware->statefulApi();

        // 2. Register the permission/role-check middleware aliases used in
        //    routes/api.php as `permission:<slug>` and `role:<slug>`:
        $middleware->alias([
            'permission' => EnsurePermission::class,
            'role' => EnsureRole::class,
        ]);
    })
    ->create();
